version: '2'

services:

  db:
    image: mariadb:latest
    container_name: php_db
    build: ./builds/mariadb/
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 4iouh8vLKKJED3LKj423
      MYSQL_USER: php_admin
      MYSQL_PASSWORD: l3ejn2OUHV8312flvL31

  php:
    image: php:7.1.2-apache
    container_name: php_app
    build: ./builds/php/
    ports:
      - 80:80
      - 443:443
      - 8000:8000
    volumes:
      - ../application:/var/www/html
    tty: true
    depends_on:
      - db

  ansible:
    image: python:2.7
    container_name: ansible
    build: ./builds/ansible/
    volumes:
      - ../playbooks:/root/playbooks
      - ../aws_certs:/root/.ssh
    volumes_from:
      - php
    tty: true
